FROM python:3
MAINTAINER Xingyan Kuang xyk7412@gmail.com
ADD downloadImage.py /
ADD utils /utils
RUN pip install pandas --upgrade \
    numpy  --upgrade \
    datetime  --upgrade \
    requests --upgrade
